-- Truck Driver Incentive Program Database Schema
-- Team 15

DROP SCHEMA IF EXISTS Team15_DB;
CREATE SCHEMA Team15_DB;
USE Team15_DB;

CREATE TABLE USERS (
  user_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  phone VARCHAR(50),
  status ENUM('active','locked','disabled') NOT NULL DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SPONSORORGANIZATION (
  org_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  org_name VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  org_status ENUM('active','disabled') NOT NULL DEFAULT 'active'
);

CREATE TABLE SPONSORUSERS (
  user_id BIGINT UNSIGNED PRIMARY KEY,
  org_id BIGINT UNSIGNED NOT NULL,

  FOREIGN KEY (user_id) REFERENCES USERS(user_id),
  FOREIGN KEY (org_id) REFERENCES SPONSORORGANIZATION(org_id)
);

# Subtype of USERS
CREATE TABLE DRIVERS (
  user_id BIGINT UNSIGNED PRIMARY KEY,
  org_id BIGINT UNSIGNED NOT NULL,
  driver_status ENUM('active','dropped') NOT NULL DEFAULT 'active',

  FOREIGN KEY (user_id) REFERENCES USERS(user_id),
  FOREIGN KEY (org_id) REFERENCES SPONSORORGANIZATION(org_id)
);

# Subtype of USERS
CREATE TABLE ADMIN (
  user_id BIGINT UNSIGNED PRIMARY KEY,

  FOREIGN KEY (user_id) REFERENCES USERS(user_id)
);

CREATE TABLE DRIVERAPPLICATIONS (
  application_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  org_id BIGINT UNSIGNED NOT NULL,
  application_status ENUM('PENDING','APPROVED','REJECTED','REVOKED') NOT NULL DEFAULT 'PENDING',
  application_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  decision_reason VARCHAR(225),

  FOREIGN KEY (user_id) REFERENCES USERS(user_id),
  FOREIGN KEY (org_id) REFERENCES SPONSORORGANIZATION(org_id)
);

CREATE TABLE PURCHASES (
  purchase_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,   -- driver user_id
  org_id BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (user_id) REFERENCES DRIVERS(user_id),
  FOREIGN KEY (org_id) REFERENCES SPONSORORGANIZATION(org_id)
);

CREATE TABLE PURCHASEITEMS (
  purchase_item_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  purchase_id BIGINT UNSIGNED NOT NULL,
  product_id VARCHAR(200) NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  product_name VARCHAR(225) NOT NULL,
  points_cost INT NOT NULL,           -- per single unit

  FOREIGN KEY (purchase_id) REFERENCES PURCHASES(purchase_id)
);

CREATE TABLE DRIVERPOINTBALANCES (
  user_id BIGINT UNSIGNED PRIMARY KEY, -- driver user_id
  current_points INT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  FOREIGN KEY (user_id) REFERENCES DRIVERS(user_id)
);

CREATE TABLE POINTTRANSACTIONS (
  transaction_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,      -- driver user_id
  org_id BIGINT UNSIGNED NOT NULL,
  point_change INT NOT NULL,
  reason VARCHAR(225) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  actor_user_id BIGINT UNSIGNED NOT NULL,

  FOREIGN KEY (user_id) REFERENCES DRIVERS(user_id),
  FOREIGN KEY (org_id) REFERENCES SPONSORORGANIZATION(org_id),
  FOREIGN KEY (actor_user_id) REFERENCES USERS(user_id)
);

CREATE TABLE AUDITLOG (
  audit_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  action_type VARCHAR(200) NOT NULL, -- should be filled automatically by trigger
  actor_user_id BIGINT UNSIGNED NOT NULL,
  actee_user_id BIGINT UNSIGNED NOT NULL,
  time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  FOREIGN KEY (actor_user_id) REFERENCES USERS(user_id),
  FOREIGN KEY (actee_user_id) REFERENCES USERS(user_id)
);

CREATE TABLE NOTIFICATIONS (
  notification_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
);